### ISSUE TITLE
Unclear about wireguard.

### ISSUE THREAD

**Issue by sa6kad** [Archef2000/pivpn-docker#1]
Hello. Thanks for a great container!
It is a little bit unclear how configure wireguard mode. Namely what volumes should be used. If possible, could you please post here on Github an examole docker/compose config for a working wireguard VPN. 

Thank you.

**Comment by archef2000** [comment]
hello sorry form answering so late but you just need to mount the /etc/wireguard and /home/pivpn/configs directories

**Comment by archef2000** [comment]
But I recommend https://github.com/WeeJeWel/wg-easy it is not made by me but it has a Web UI and has nice user config

**Comment by archef2000** [comment]
will do
