### ISSUE TITLE
How do I reload server.conf

### ISSUE THREAD

**Issue by Loongle** [Archef2000/pivpn-docker#7]
I  change cipher, but I couldn't execute `sudo systemctl restart openvpn` and make it work

Run the `docker restart` command to restart the client file and generate the original cipher file again

**Comment by archef2000** [comment]
Sorry for waiting. It took me some time to figure it out.

As pivpn regenerates the server config each time you could copy the template to the host using ```docker cp pivpn:/usr/local/src/pivpn/files/etc/openvpn/server_config.txt ./``` edit it and mount it into the container at the same path to override it. So it regenerates the file with your cipher option.
